const job = [
  {
    title: "UX UI Designer",
    company: "Great Vibes",
    sector: "Information Technology",
    location: "chennai, Tamilnadu, India",
    mode: "in-office",
    type: "Part-Time",
    time: "9.00am - 5.00pm IST",
    experience: "1-2 years",
    currency: "INR (₹)",
    salary: "30,000 - 60,000 / Month",
    employees: "51-200",
    applyType: "quick",
  },
  {
    title: "Developer",
    company: "Great Vibes",
    sector: "Information Technology",
    location: "chennai, Tamilnadu, India",
    mode: "in-office",
    type: "Part-Time",
    time: "9.00am - 5.00pm IST",
    experience: "1-2 years",
    currency: "INR (₹)",
    salary: "50,000 - 70,000 / Month",
    employees: "51-200",
    applyType: "external",
  },
  {
    title: "Interaction Designer",
    company: "Great Vibes",
    sector: "Information Technology",
    location: "chennai, Tamilnadu, India",
    mode: "in-office",
    type: "Part-Time",
    time: "9.00am - 5.00pm IST",
    experience: "1-2 years",
    currency: "INR (₹)",
    salary: "30,000 - 50,000 / Month",
    employees: "51-200",
    applyType: "quick",
  },
  {
    title: "SEO Analyst",
    company: "Great Vibes",
    sector: "Information Technology",
    location: "chennai, Tamilnadu, India",
    mode: "in-office",
    type: "Part-Time",
    time: "9.00am - 5.00pm IST",
    experience: "1-2 years",
    currency: "INR (₹)",
    salary: "30,000 - 50,000 / Month",
    employees: "51-200",
    applyType: "external",
  },
];

export default job;
